export const TestList = [
    {
        "channelList":[],
        "createDate":1613693039000,
        "drift":0,
        "id":13,
        "modifyDate":1613693042000,
        "moduleType":1,
        "payMode":1,
        "payName":"微信支付",
        "payType":"WX_PAY",
        "status":0
    },
    {
        "channelList":[
            {
                "channelId":217,
                "isFornew":0,
                "name":"火山支付威力_支付宝红包_711",
                "ratio":0
            },
            {
                "channelId":223,
                "isFornew":0,
                "name":"汇银支付威力_支付宝原生_802",
                "ratio":100
            },
            {
                "channelId":214,
                "isFornew":0,
                "name":"一路发威力_支付宝红包_1501",
                "ratio":0
            },
            {
                "channelId":149,
                "isFornew":0,
                "name":"能支付威力_209支付宝直播",
                "ratio":0
            }
        ],
        "createDate":1613693083000,
        "drift":0,
        "id":14,
        "modifyDate":1613693085000,
        "moduleType":1,
        "payMode":1,
        "payName":"支付宝支付",
        "payType":"ALI_PAY",
        "status":1
    },
    {
        "channelList":[
            {
                "channelId":142,
                "isFornew":0,
                "name":"聚合支付威力_大额卡卡银联",
                "ratio":20
            },
            {
                "channelId":143,
                "isFornew":0,
                "name":"聚合支付威力_小额卡卡银联",
                "ratio":50
            },
            {
                "channelId":179,
                "isFornew":0,
                "name":"巅峰威力_8027卡转卡",
                "ratio":30
            }
        ],
        "createDate":1621934087000,
        "drift":0,
        "id":15,
        "modifyDate":1621934089000,
        "moduleType":1,
        "payMode":1,
        "payName":"银联支付",
        "payType":"UNION_PAY",
        "status":1
    },
    {
        "channelList":[
            {
                "channelId":174,
                "isFornew":0,
                "name":"小马_微信YY_8002",
                "ratio":0
            },
            {
                "channelId":175,
                "isFornew":0,
                "name":"小马_微信原生_8005",
                "ratio":0
            },
            {
                "channelId":221,
                "isFornew":0,
                "name":"鸿支付威力_微信内付_501",
                "ratio":0
            },
            {
                "channelId":263,
                "isFornew":0,
                "name":"龙头支付_微信原生H5",
                "ratio":100
            }
        ],
        "createDate":1613693039000,
        "drift":0,
        "id":16,
        "modifyDate":1613693042000,
        "moduleType":2,
        "payMode":1,
        "payName":"微信支付",
        "payType":"WX_PAY",
        "status":1
    },
    {
        "channelList":[
            {
                "channelId":133,
                "isFornew":0,
                "name":"蚂蚁威力_8044抗投原生支付宝",
                "ratio":0
            },
            {
                "channelId":214,
                "isFornew":0,
                "name":"一路发威力_支付宝红包_1501",
                "ratio":0
            },
            {
                "channelId":217,
                "isFornew":0,
                "name":"火山支付威力_支付宝红包_711",
                "ratio":0
            },
            {
                "channelId":223,
                "isFornew":0,
                "name":"汇银支付威力_支付宝原生_802",
                "ratio":0
            },
            {
                "channelId":240,
                "isFornew":0,
                "name":"沧澜支付宝威力_116",
                "ratio":0
            },
            {
                "channelId":149,
                "isFornew":0,
                "name":"能支付威力_209支付宝直播",
                "ratio":0
            },
            {
                "channelId":247,
                "isFornew":0,
                "name":"罗宾威力支付_121支付宝纯视频",
                "ratio":0
            },
            {
                "channelId":261,
                "isFornew":0,
                "name":"龙头支付_支付宝原生H5",
                "ratio":100
            },
            {
                "channelId":268,
                "isFornew":0,
                "name":"龙头威力支付_8005支付宝商城小店固额H5",
                "ratio":0
            }
        ],
        "createDate":1613693083000,
        "drift":0,
        "id":17,
        "modifyDate":1613693085000,
        "moduleType":2,
        "payMode":1,
        "payName":"支付宝支付",
        "payType":"ALI_PAY",
        "status":1
    },
    {
        "channelList":[
            {
                "channelId":142,
                "isFornew":0,
                "name":"聚合支付威力_大额卡卡银联",
                "ratio":0
            },
            {
                "channelId":143,
                "isFornew":0,
                "name":"聚合支付威力_小额卡卡银联",
                "ratio":0
            },
            {
                "channelId":179,
                "isFornew":0,
                "name":"巅峰威力_8027卡转卡",
                "ratio":100
            },
            {
                "channelId":185,
                "isFornew":0,
                "name":"蚂蚁威力_小额卡转卡_8053",
                "ratio":0
            },
            {
                "channelId":186,
                "isFornew":0,
                "name":"蚂蚁威力_大额卡转卡_8054",
                "ratio":0
            },
            {
                "channelId":213,
                "isFornew":0,
                "name":"沧澜威力_001卡转卡",
                "ratio":0
            }
        ],
        "createDate":1621934087000,
        "drift":0,
        "id":18,
        "modifyDate":1621934089000,
        "moduleType":2,
        "payMode":1,
        "payName":"银联支付",
        "payType":"UNION_PAY",
        "status":1
    },
    {
        "channelList":[
            {
                "channelId":271,
                "isFornew":0,
                "name":"boss云微信支付",
                "ratio":100
            },
            {
                "channelId":272,
                "isFornew":0,
                "name":"boss云微信支付",
                "ratio":0
            }
        ],
        "createDate":1613693039000,
        "drift":0,
        "id":19,
        "modifyDate":1613693042000,
        "moduleType":5,
        "payMode":1,
        "payName":"微信支付",
        "payType":"WX_PAY",
        "status":1
    },
    {
        "channelList":[
            {
                "channelId":214,
                "isFornew":0,
                "name":"一路发威力_支付宝红包_1501",
                "ratio":0
            },
            {
                "channelId":246,
                "isFornew":0,
                "name":"罗宾威力支付_81支付宝H5UID转账模式",
                "ratio":0
            },
            {
                "channelId":248,
                "isFornew":0,
                "name":"罗宾威力支付_74支付宝小额UID",
                "ratio":0
            },
            {
                "channelId":261,
                "isFornew":0,
                "name":"龙头支付_支付宝原生H5",
                "ratio":0
            },
            {
                "channelId":262,
                "isFornew":0,
                "name":"龙头支付_支付宝YY",
                "ratio":0
            },
            {
                "channelId":171,
                "isFornew":0,
                "name":"视频威力公用青蛙威力_932支付宝",
                "ratio":0
            },
            {
                "channelId":227,
                "isFornew":0,
                "name":"青蛙威力_ZFBH5",
                "ratio":0
            },
            {
                "channelId":255,
                "isFornew":0,
                "name":"一路发新威力支付_787支付宝固码",
                "ratio":0
            },
            {
                "channelId":273,
                "isFornew":0,
                "name":"boss云支付宝支付",
                "ratio":0
            },
            {
                "channelId":223,
                "isFornew":0,
                "name":"汇银支付威力_支付宝原生_8009",
                "ratio":100
            }
        ],
        "createDate":1613693083000,
        "drift":0,
        "id":20,
        "modifyDate":1613693085000,
        "moduleType":5,
        "payMode":1,
        "payName":"支付宝支付",
        "payType":"ALI_PAY",
        "status":1
    },
    {
        "channelList":[
            {
                "channelId":142,
                "isFornew":0,
                "name":"聚合支付威力_大额卡卡银联",
                "ratio":0
            },
            {
                "channelId":143,
                "isFornew":0,
                "name":"聚合支付威力_小额卡卡银联",
                "ratio":0
            },
            {
                "channelId":179,
                "isFornew":0,
                "name":"巅峰威力_8027卡转卡",
                "ratio":0
            },
            {
                "channelId":213,
                "isFornew":0,
                "name":"沧澜威力_001卡转卡",
                "ratio":100
            }
        ],
        "createDate":1621934087000,
        "drift":0,
        "id":21,
        "modifyDate":1621934089000,
        "moduleType":5,
        "payMode":1,
        "payName":"银联支付",
        "payType":"UNION_PAY",
        "status":1
    }
]