const CHANGE_BANNER_LIST = 'CHANGE_BANNER_LIST' //修改轮播图
const CHANGE_PRO_LIST = 'CHANGE_PRO_LIST'  //修改列表
const CHANGE_KIND_LIST = 'CHANGE_KIND_LIST' //修改分类

export {
    CHANGE_BANNER_LIST,
    CHANGE_PRO_LIST,
    CHANGE_KIND_LIST
}