const CHANGE_CPLLAPSED = "CHANGE_CPLLAPSED" //左侧菜单栏切换
const CHANGE_COLOR = "CHANGE_COLOR" //主题颜色

//登录相关
const CHANGE_ADMIN_NAME = 'CHANGE_ADMIN_NAME'
const CHANGE_ADMIN_ROLE = 'CHANGE_ADMIN_ROLE'
const CHANGE_ADMIN_TOKEN = 'CHANGE_ADMIN_TOKEN'
const CHANGE_LOGIN_STATE = 'CHANGE_LOGIN_STATE'

export {
    CHANGE_CPLLAPSED ,
    CHANGE_COLOR,
    CHANGE_ADMIN_NAME,
    CHANGE_ADMIN_ROLE,
    CHANGE_ADMIN_TOKEN,
    CHANGE_LOGIN_STATE
}