
const CHANGE_COLLAPSED = 'CHANGE_COLLAPSED' //左侧菜单收缩变量
const CHANGE_COLOR = 'CHANGE_COLOR' // 修改主题色


//登录相关
const CHANGE_ADMINNAME = 'CHANGE_ADMINNAME' //修改用户名称
const CHANGE_LOGINSTATE = 'CHANGE_LOGINSTATE' // 修改用户登录状态
const CHANGE_TOKEN = 'CHANGE_TOKEN' //修改用户token
const CHANGE_ROLE = 'CHANGE_ROLE' //修改用户role

export {
    CHANGE_COLLAPSED,
    CHANGE_COLOR,
    CHANGE_ADMINNAME,
    CHANGE_LOGINSTATE,
    CHANGE_TOKEN,
    CHANGE_ROLE
}