const CHANGE_COLLAPSED = 'CHANGE_COLLAPSED'
const CHANGE_THEME_COLOR = 'CHANGE_THEME_COLOR'

//用户登录信息相关
const CHANGE_ADMIN_NAME = 'CHANGE_ADMIN_NAME'
const CHANGE_ROLE = 'CHANGE_ROLE'
const CHANGE_LOGIN_STATE = 'CHANGE_LOGIN_STATE'
const CHANGE_TOKEN = 'CHANGE_TOKEN'

export {
    CHANGE_COLLAPSED,
    CHANGE_THEME_COLOR,
    CHANGE_ADMIN_NAME,
    CHANGE_ROLE,
    CHANGE_LOGIN_STATE,
    CHANGE_TOKEN
}