const CHANGE_COLLAPSED = "CHANGE_COLLAPSED"
const CHANGE_USERNAME = "CHANGE_USERNAME"
const CHANGE_ROLE = "CHANGE_ROLE"
const CHANGE_LOGINSTATE = "CHANGE_LOGINSTATE"
const CHANGE_TOKEN = "CHANGE_TOKEN"

export {
    CHANGE_COLLAPSED,
    CHANGE_USERNAME,
    CHANGE_ROLE,
    CHANGE_LOGINSTATE,
    CHANGE_TOKEN
}