const CHNAGE_BANNER_LIST = 'CHNAGE_BANNER_LIST'
const CHNAGE_PRO_LIST = 'CHNAGE_PRO_LIST'
const CHNAGE_KIND_LIST = 'CHNAGE_KIND_LIST'

export {
    CHNAGE_BANNER_LIST,
    CHNAGE_PRO_LIST,
    CHNAGE_KIND_LIST
}