// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import DashboardOutlined from '/var/lib/jenkins/workspace/pay-manager-web/node_modules/@ant-design/icons/es/icons/DashboardOutlined';
import SettingOutlined from '/var/lib/jenkins/workspace/pay-manager-web/node_modules/@ant-design/icons/es/icons/SettingOutlined';
import ShopOutlined from '/var/lib/jenkins/workspace/pay-manager-web/node_modules/@ant-design/icons/es/icons/ShopOutlined';
import MoneyCollectOutlined from '/var/lib/jenkins/workspace/pay-manager-web/node_modules/@ant-design/icons/es/icons/MoneyCollectOutlined';
import NodeIndexOutlined from '/var/lib/jenkins/workspace/pay-manager-web/node_modules/@ant-design/icons/es/icons/NodeIndexOutlined';
export default { DashboardOutlined, SettingOutlined, ShopOutlined, MoneyCollectOutlined, NodeIndexOutlined };
